# Generated by Django 4.2.11 on 2025-11-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_profiles/'),
        ),
    ]
